---
author: Murilo Teixeira Silva
title: Murilo T. Silva, M.Eng
tagline: Radar and Remote Sensing Group | Memorial University of Newfoundland
email: murilots@mun.ca
affiliation: "Radar and Remote Sensing Group\nDepartment of Electrical and Computer
  Engineering\nFaculty of Engineering and Applied Science\nMemorial University of
  Newfoundland   \nSt. John's, NL, Canada\n"
baseurl: ''
url: http://murilotsilva.github.io
show_excerpts: true
twitter_username: murilotsilva
linkedin_username: murilots
github_username: murilotsilva
facebook_username: murilotxs90
header_pages:
- about.markdown
- publications.md
- blog/index.html
theme: minima
github:
- 'repository: murilotsilva/murilotsilva.github.io'
- metadata
plugins:
- jekyll-feed
- jekyll-seo-tag
lsi: false
safe: true
source: ''
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
